//! Article-specific adapter; typesetting and native widgets live in Makepad.
pub use makepad_markdown_widgets::math_view::*;
use article_core::document::{Document, Block};

/// Only generated by native_block_html after source HTML has been sanitized.
pub fn native_block_html(document: &Document, block: &Block) -> String {
    let size = if document.large_type { 16.0 } else { 14.0 };
    let ink = document.theme.colors().1;
    document.block_html_with_math(block, |formula| formula_html(formula, size, ink))
}

